language: php
php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

install:
    - travis_retry composer install --no-progress --prefer-dist

script:
    - vendor/bin/tester tests -s

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
